# Generated by Django 4.1.4 on 2022-12-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('attempted_id', models.IntegerField()),
                ('cand_name', models.CharField(max_length=50)),
                ('cand_email', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=3)),
            ],
        ),
    ]
