# Generated by Django 4.1.4 on 2022-12-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_retrieve_file_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.CharField(max_length=50),
        ),
    ]
