# Generated by Django 4.1.4 on 2023-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attempted_id',
            field=models.CharField(max_length=50),
        ),
    ]
